### ISSUE TITLE
Missing memorystick_small.asm in /Tools/filetransfer.asm

### ISSUE THREAD

**Issue by gd-99** [gotaproblem/Z80Playground#1]
Had a go at compiling filetransfer.asm, but got an error that memorystick_small.asm could not be found. Down at the bottom of the filetransfer.asm file I see there is an include "memorystick_small.asm", but I cant find it in the repository.

Would it possible to upload it when you have a mo?

Many thanks,

Glyn.

**Comment by gotaproblem** [comment]
The current source will not work as it is incomplete (as you found). Treat the current source as a placeholder. When I have time, I will update the source tree
