### ISSUE TITLE
Reinstating the Monitor - Jump (to address) function

### ISSUE THREAD

**Issue by gd-99** [gotaproblem/Z80Playground#3]
The extensive monitor functions are missing a "jump" to a memory function. Looking in commands.asm, the jump functionality is built in but the command has been removed from the command table.

Reinstating the jump commands in the table by following the existing command table formatting, will restore the jump function, however as it stands there is a small bug in the actual jump command function. The bug is in the print command usage bit of code.

The existing code:
cmd_jump_error:
ld		hl, (str_cmd_jump_err)

Correct this to by removing the "()":
cmd_jump_error:
ld		hl, str_cmd_jump_err

Following this correction the jump command works correctly on my board.

**Comment by gotaproblem** [comment]
Thankyou for highlighting the problem and providing a solution. The Monitor has been amended with your fix
